server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crow?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1Mysql@23
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
#    type: com.alibaba.druid.pool.DruidDataSource
